In [33]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

In [9]:
A=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x=np.matrix([[1],[0],[0]])
print(A,"kali ", x, end="")

[[1 2 3]
 [4 5 6]
 [7 8 9]] kali  [[1]
 [0]
 [0]]

In [3]:
A*x

matrix([[1],
        [4],
        [7]])

In [10]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
x=np.array([[1],[0],[0]])

In [11]:
A.dot(x)

array([[1],
       [4],
       [7]])

In [13]:
A.dot(x)

array([[1],
       [4],
       [7]])

In [18]:
B=np.ones((3,3))

In [15]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
type(B)

numpy.ndarray

In [20]:
x=np.ones((3,1))

In [21]:
x

array([[1.],
       [1.],
       [1.]])

In [22]:
B*x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
B.dot(x)

array([[3.],
       [3.],
       [3.]])

In [35]:
n=8
x=np.arange(n)
k=5
y=as_strided(x,(k,n-k+1),(x.itemsize,)*2)

In [36]:
y

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [37]:
x.itemsize

8

In [40]:
as_strided(x,(5,4),(8,4))

array([[          0,  4294967296,           1,  8589934592],
       [          1,  8589934592,           2, 12884901888],
       [          2, 12884901888,           3, 17179869184],
       [          3, 17179869184,           4, 21474836480],
       [          4, 21474836480,           5, 25769803776]])

In [46]:
x=np.arange(16)

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
y=as_strided(x,(7,4),(7,4))
y

array([[                 0,         4294967296,                  1,
                8589934592],
       [               256,      2199023255552,                512,
             3298534883328],
       [            131072,    844424930131968,             196608,
          1125899906842624],
       [          50331648, 288230376151711744,           67108864,
        360287970189639680],
       [       17179869184,                  4,        21474836480,
                         5],
       [     5497558138880,               1280,      6597069766656,
                      1536],
       [  1688849860263936,             393216,   1970324836974592,
                    458752]])

In [53]:
x[::2]=99

In [54]:
x

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9, 99, 11, 99, 13, 99, 15])

In [55]:
y

array([[                 99,          4294967296,                   1,
               425201762304],
       [                256,     108851651149824,               25344,
              3298534883328],
       [            6488064,     844424930131968,              196608,
          27866022694354944],
       [           50331648, 7133701809754865664,          1660944384,
         360287970189639680],
       [       425201762304,                  99,         21474836480,
                          5],
       [      5497558138880,                1280,     108851651149824,
                      25344],
       [  27866022694354944,             6488064,    1970324836974592,
                     458752]])

In [61]:
x,y=np.meshgrid(np.arange(2),np.arange(2))

In [62]:
x

array([[0, 1],
       [0, 1]])

In [58]:
np.arange(2)

array([0, 1])

In [60]:
np.meshgrid(np.arange(2))

[array([0, 1])]

In [63]:
y

array([[0, 0],
       [1, 1]])

In [64]:
x

array([[0, 1],
       [0, 1]])

In [75]:
x=np.array([0,1])

In [76]:
y=np.array([0,1,2])

In [77]:
x

array([0, 1])

In [78]:
y

array([0, 1, 2])

In [79]:
X,Y=np.meshgrid(x,y)

In [80]:
X

array([[0, 1],
       [0, 1],
       [0, 1]])

In [81]:
Y

array([[0, 0],
       [1, 1],
       [2, 2]])

In [82]:
X+Y

array([[0, 1],
       [1, 2],
       [2, 3]])

In [85]:
x+y[:,None]

array([[0, 1],
       [1, 2],
       [2, 3]])