In [23]:
import numpy as np

In [2]:
angka=[1,2,3]

In [3]:
angkanp = np.array(angka)

In [4]:
angkanp

array([1, 2, 3])

In [5]:
angka*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
angkanp*3

array([3, 6, 9])

In [7]:
versilist=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
versinp=np.array(versilist)

In [9]:
versinp

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [26]:
np.matrix(versinp)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
# Bilangan distrbusi uniform

In [31]:
np.random.rand(7)

array([0.14476854, 0.17212177, 0.00157575, 0.13026462, 0.80873735,
       0.37910899, 0.80410799])

In [32]:
np.random.rand(5,4)

array([[0.95743738, 0.69012068, 0.92706361, 0.47620769],
       [0.22967468, 0.60296309, 0.84037054, 0.27310572],
       [0.44524711, 0.73474639, 0.26395977, 0.5322174 ],
       [0.96623086, 0.15422329, 0.93208152, 0.7776825 ],
       [0.20772266, 0.73737002, 0.89487825, 0.67603241]])

In [33]:
# distribusi normal
np.random.randn(10)

array([ 0.91273645, -1.30766481, -1.36772343,  1.2042536 , -1.62297016,
       -1.60820125, -2.25178672,  0.15127489, -1.89770854,  0.09736904])

In [34]:
np.random.randn(4,4)

array([[-0.34690847, -1.17104093, -1.53907889, -0.50877016],
       [ 2.61400271,  1.43319364, -0.29610287, -0.12959342],
       [ 1.71854408,  0.2399442 ,  0.81976757, -0.56625384],
       [ 0.02237047,  1.37416958, -0.22707196, -1.8419911 ]])

In [37]:
#import library lebih singkat
from numpy.random import randn, randint

In [36]:
randn(6,2)

array([[ 0.68778716,  0.95455211],
       [ 1.32962539,  1.00213467],
       [-0.59196294,  1.20130177],
       [-1.05630994, -0.96612332],
       [-0.05723565,  0.55583721],
       [ 0.06657675, -2.23820231]])

In [40]:
randint(0,10,5)

array([8, 2, 5, 0, 7])

In [41]:
bilangan = randint(0,100,20)

In [42]:
bilangan

array([52, 14, 92, 53, 38, 76, 40,  7, 33, 63, 45, 11, 15, 85, 93, 83, 79,
       36, 18, 73])

In [43]:
bilangan.reshape(4,5)

array([[52, 14, 92, 53, 38],
       [76, 40,  7, 33, 63],
       [45, 11, 15, 85, 93],
       [83, 79, 36, 18, 73]])

In [45]:
randint(0,10,25)

array([7, 8, 5, 5, 8, 7, 1, 7, 7, 3, 4, 8, 3, 7, 4, 5, 5, 3, 7, 2, 0, 4,
       9, 4, 6])

In [51]:
coba =randint(0,10,20).reshape(2,10)

In [52]:
coba

array([[1, 5, 0, 8, 8, 5, 9, 7, 7, 9],
       [5, 2, 2, 3, 5, 0, 0, 8, 9, 2]])

In [53]:
coba1d = randint(0,100,20)

In [63]:
coba2d = randint(0,100,20).reshape(4,5)

In [64]:
coba2d

array([[72, 48,  7, 24, 22],
       [29, 64, 60, 25, 52],
       [66, 79, 30, 50, 30],
       [18, 20, 84, 49, 48]])

In [56]:
coba1d.max()

93

In [57]:
coba2d.max()

92

In [58]:
coba1d.argmax()

0

In [59]:
coba2d.argmax()

16

In [60]:
coba1d.argmin()

17

In [62]:
coba1d.shape

(20,)

In [65]:
coba2d.shape

(4, 5)

In [70]:
coba =np.arange(0,11)

In [73]:
coba

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
coba2 =coba[:6]

In [76]:
coba2

array([0, 1, 2, 3, 4, 5])

In [77]:
coba2[:]=100

In [78]:
coba2

array([100, 100, 100, 100, 100, 100])

In [79]:
coba

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [83]:
coba2 =coba.copy()

In [85]:
coba2

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [88]:
bil2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [89]:
bil2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
bil2d[1][2]

6

In [95]:
bil2d[0]

array([1, 2, 3])

In [97]:
bil2d[2,2]

9

In [98]:
bil2d[1:2,1:]

array([[5, 6]])

In [113]:
bil = np.arange(1,11)

In [114]:
bil

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
angkaT = bil > 5

In [102]:
angkaT

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [116]:
bil[bil>5]

array([ 6,  7,  8,  9, 10])

In [118]:
bil[bil<8]

array([1, 2, 3, 4, 5, 6, 7])

# Operasi di Numpy

In [119]:
import numpy as np

In [123]:
coba = np.arange(1,11)

In [124]:
coba

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
coba+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
coba_list=[1,2,3,4,5,6,7]

In [128]:
coba_list*2

[1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7]

In [129]:
coba-100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [130]:
coba/coba

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [131]:
coba-coba

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [132]:
coba/coba

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [133]:
np.mean(coba)

5.5

In [ ]:
np.array_split()